### ISSUE TITLE
switch c-extensions to cython

### ISSUE THREAD

**Issue by justincely** [justincely/lightcurve#21]
building the c-extensions directly in both python2.7 and 3.X is not working (seen in the travis builds) and according to the python c-api, it's a bit tricky. https://docs.python.org/3/howto/cporting.html

Trying to build cython instead may provide a easier/faster implementation.

**Comment by cmillion** [comment]
Looks like the stuff in stis_cal.cc is possibly vectorizable. (I see loops.) FWIW, I've found that speed improvements have almost always been comparable by vectorizing things with numpy operations as if I use Cython. See, e.g., https://github.com/cmillion/gPhoton/blob/master/gPhoton/gnomonic.py

**Comment by justincely** [comment]
thanks for the thoughts Chase - I've tried thinking about this one a lot but in the end i don't think i can vectorize it.  The main purpose of the functions are to map individual photon events through a 2D image according to their x,y positions - which seems un-vectorizable to me. If you think of a way, let me know - but for now I've got a cython extension working.

**Comment by justincely** [comment]
Closed with the cython extension working

**Comment by cmillion** [comment]
Can you describe what you mean by "map through a 2D image?"

Of course, if it's now working fine like it is, there's no reason to work on a more clever solution simply because it's more clever.
